name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout ðŸ›Žï¸
  #       uses: actions/checkout@v3
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Run unit tests
  #       run: |
  #         mkdir src/environments
  #         echo "export const environment = { production: true, apiKey: '${{ secrets.API_KEY_RAPID_ANIME }}' };">src/environments/environment.ts
  #         npm run test
  #     - name: Generate coverage report
  #       run: npm run coverage
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3
      - name: Build
        run: |
          ls
          npm ci
          mkdir src/environments
          echo "export const environment = { production: true, apiKey: '${{ secrets.API_KEY_RAPID_ANIME }}' };">src/environments/environment.ts
          npm run build
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/
  Lighthouse:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    name: Lighthouse
    steps:
      - name: run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: https://edouardglx.github.io/poc3_Angular/
          uploadArtifacts: true
